config/routes.rb
Arbeit::Application.routes.draw do

  # Routes for main resources
  resources :domains
  resources :projects
  resources :tasks
  resources :assignments
  resources :users
  resources :sessions
  
  # Authentication routes
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'reset_password/:id' => 'users#reset_password', :as => :reset_password
  match 'password_reset' => 'users#password_reset', :as => :password_reset
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  # Semi-static page routes
  match 'home' => 'home#home', :as => :home
  match 'search' => 'home#search', :as => :search
  match 'cylon' => 'errors#cylon', :as => :cylon
  match 'statics' => 'statics#show', :as => 'statics'
  
  # Set the root url
  root :to => 'home#home'  
  
  # Named routes
  match 'completed/:id' => 'tasks#complete', :as => :complete
  match 'incomplete/:id' => 'tasks#incomplete', :as => :incomplete
  
  # Last route in routes.rb that essentially handles routing errors
  match '*a', :to => 'errors#routing'
end

app/views/partials/_completed_task.html.erb
<div class="completed_task">
	<p>
		<div class="tl_name">
			<span class="smtext">
				<%= link_to(completed_task.name, task_path(completed_task)) %><br />
				<em>(<%= completed_task.project.name %>)</em>
			</span>
		</div>
		<div class="tl_date">
			<span class="smtext"><%= completed_task.due_on.strftime("%b %d") %></span>
		</div>
		<div class="tl_controls">
			<%= link_to(image_tag("/images/icons/check_green.gif", border: 0), incomplete_path(task_item.id), method: :put) %>
			&nbsp;
			<%= link_to(image_tag("/images/icons/close.gif", border: 0), task_path(task_item), method: :delete, confirm: 'Delete this task?') %>
		</div>
	</p>
</div>

app/views/partials/_footer.html.erb
<div id="footer">

	<%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'About Arbeit', statics_path(:page => 'about'.parameterize.gsub(/-/, '_')) %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'Contact Us', statics_path(:page => 'contact'.parameterize.gsub(/-/, '_')) %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'Privacy Policy', statics_path(:page => 'privacy'.parameterize.gsub(/-/, '_')) %>
	
	<div id="copy">
		Webmaster: <%= mail_to("profh@cmu.edu", "Klingon Code Warrior", encode: "javascript") %> 
		&nbsp;&nbsp;&copy 2013
	</div>

</div>

app/views/partials/_login_form.html.erb
<% form_tag sessions_path do %>
  <p>
    <%= label_tag :login %>
    <%= text_field_tag :login %>
		<br>
		<!-- TODO: verify that encoding the passwords as Base64 strings is sufficiently secure -->
    <%= label_tag :password %>
    <%= password_field_tag :password %>
		<br>
		<span class="login_button"><%= submit_tag "Log in" %></span>
	</p>
<% end %>

app/views/partials/_project_item.html.erb
<div class="project_item">
	<p>
		<span class="smtext"><strong><%= link_to(project_item.name, project_path(project_item)) %></strong></span><br>
		<span class="smtext"><%= raw(truncate(project_item.description, length: 100, omission: (link_to "...(more)", project_item))) %></span>
	</p>
</div>

app/views/partials/_task_dg.html.erb
<table class="datagrid">
  <thead class="datagrid">
    <th width="165">Title</th>
    <th width="65" align="center">Date</th>
	<th width="65" align="center">Time</th>
    <th width="65" align="center">Priority</th>
	<th width="65" align="center">Done?</th>
  </thead>
  
<% for task in @tasks %>
  <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
    <td>&nbsp;<%= link_to task.name, task_path(task)  %></td>
    <td align="center"><%= task.due_on.strftime("%m/%d") %></td>
	<td align="center"><%= task.due_on.strftime("%I:%M %p") %></td>
    <td align="center"><%= get_priority_name(task.priority) %></td>
    <td align="center"><%= get_task_status(task.completed)  %></td>
  </tr>
<% end %>
</table>
<p class="supertiny">&nbsp;</p>
<span class="smtext"><%# will_paginate @tasks %></span>
<p class="supertiny">&nbsp;</p>

app/views/partials/_task_item.html.erb
<% unless task_item.nil? %>
	<div class="<%= get_priority_class(task_item.priority)  %>">
		<p>
			<div class="tl_name">
				<span class="smtext">
					<%= link_to(task_item.name, task_path(task_item)) %><br />
					<em>(<%= task_item.project.name %>)</em>
				</span>
			</div>
			<div class="tl_date">
				<span class="smtext"><%= task_item.due_on.strftime("%b %d") %></span>
			</div>
			<div class="tl_controls">
				<%= link_to(image_tag("/images/icons/check_green.gif", :border => 0), complete_path(task_item.id), :method => :put) %>
				&nbsp;
				<%= link_to(image_tag("/images/icons/close.gif", :border => 0), task_path(task_item), :method => :delete, :confirm => 'Delete this task?') %>
			</div>
		</p>
	</div>
<% end %>

app/views/partials/_task_listing.html.erb
<table class="datagrid">
  <thead class="datagrid">
    <th width="200">Title</th>
    <th width="70" align="center">Date</th>
	<th width="70" align="center">Time</th>
    <th width="70" align="center">Priority</th>
	<th width="90">&nbsp;</th>
  </thead>
  
<% for task in @tasks %>
  <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
    <td>&nbsp;<%= link_to truncate(task.name,17), task_path(task)  %></td>
    <td align="center"><%= task.due_on.strftime("%m/%d") %></td>
	<td align="center"><%= task.due_on.strftime("%I:%M %p") %></td>
    <td align="center"><%= get_priority_name(task.priority) %></td>
    <td align="center">
    	<%= link_to(image_tag("/images/icons/edit_dg.gif", border: 0), edit_task_path(task))  %>&nbsp;
    	<%= link_to(image_tag("/images/icons/close.gif", border: 0), task_path(task), confirm: 'Are you sure you wish to delete this information?', method: :delete) %>
	</td>
  </tr>
<% end %>
</table>
<p class="supertiny">&nbsp;</p>
<span class="smtext"><%= will_paginate @tasks %></span>
<p class="supertiny">&nbsp;</p>