config/routes.rb
Arbeit::Application.routes.draw do

  # Routes for main resources
  resources :domains
  resources :projects
  resources :tasks
  resources :assignments
  resources :users
  resources :sessions
  
  # Authentication routes
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'reset_password/:id' => 'users#reset_password', :as => :reset_password
  match 'password_reset' => 'users#password_reset', :as => :password_reset
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  # Semi-static page routes
  match 'home' => 'home#home', :as => :home
  match 'search' => 'home#search', :as => :search
  match 'cylon' => 'errors#cylon', :as => :cylon
  match 'statics' => 'statics#show', :as => 'statics'
  
  # Set the root url
  root :to => 'home#home'  
  
  # Named routes
  match 'completed/:id' => 'tasks#complete', :as => :complete
  match 'incomplete/:id' => 'tasks#incomplete', :as => :incomplete
  
  # Last route in routes.rb that essentially handles routing errors
  match '*a', :to => 'errors#routing'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Specify fields that can be accessible through mass assignment (not password_digest)
  attr_accessor :password, :password_confirmation
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name, :active, :role
  
  # Use built-in rails support for password protection
  # has_secure_password
  before_create :set_password_digest
    
  # Relationships
  # -----------------------------
  has_many :assignments
  has_many :projects, :through => :assignments
  has_many :completed_tasks, :class_name => "Task", :foreign_key => "completed_by"
  has_many :created_tasks, :class_name => "Task", :foreign_key => "created_by"

  # Scopes
  # -----------------------------
  scope :alphabetical, order("last_name, first_name")
  scope :active,       where('active = ?', true)
  scope :inactive,       where('active = ?', false)
  
  # Validations
  # -----------------------------
  # make sure required fields are present
  validates_presence_of :first_name, :last_name, :email  
  validates_uniqueness_of :email, :allow_blank => true
  validates_format_of :email, :with => /^[\w]([^@\s,;]+)@(([a-z0-9.-]+\.)+(com|edu|org|net|gov|mil|biz|info))$/i, :message => "is not a valid format", :allow_blank => true
  validates_presence_of :password, :on => :create 
  validates_presence_of :password_confirmation, :on => :create 
  validates_confirmation_of :password, :message => "does not match"
  validates_length_of :password, :minimum => 4, :message => "must be at least 4 characters long", :allow_blank => true
  
  # Other methods
  # -----------------------------  
  def proper_name
    first_name + " " + last_name
  end
  
  def name
    last_name + ", " + first_name
  end

  # for use in authorizing with CanCan
  ROLES = [['Administrator', :admin],['Member', :member]]

  def role?(authorized_role)
    return false if role.nil?
    role.downcase.to_sym == authorized_role
  end

  # login by email address
  def self.authenticate(email, password)
    find_by_email(email).try(:authenticate, password)
  end
  
  def update_user_attributes
    digest = self.encode_password
    query = "UPDATE users SET first_name='#{self.first_name}',last_name='#{self.last_name}',email='#{self.email}',role='#{self.role}',active='#{self.active}',password_digest='#{digest}' WHERE id=#{self.id}"
    User.connection.execute(query)
  end
  
  def self.reset_password(new_pswd, user_id)
    query = "UPDATE users SET password_digest='#{Base64.encode64(new_pswd)}' WHERE id='#{user_id}'"
    User.connection.execute(query)
  end
  
  def encode_password
    Base64.encode64(self.password)
  end
  
  def set_password_digest
    self.password_digest = encode_password
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.alphabetical.paginate(:page => params[:page]).per_page(7)
  end

  def show
    @user = User.find(params[:id])
    @user_assignments = @user.assignments.active.by_project
    @created_tasks = Task.for_creator(@user.id).by_name
    @completed_tasks = Task.for_completer(@user.id).by_name
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    authorize! :edit, @user
  end

  def create
    @user = User.new(params[:user])
    unless current_user && current_user.role?(:admin)
      @user.role = "member"
    end
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      flash[:error] = "This user could not be created."
      render "new"
    end
  end

  def update
    @user = User.find(params[:id])
    @user.first_name = params[:user][:first_name]
    @user.last_name = params[:user][:last_name]
    @user.email = params[:user][:email]
    @user.role = params[:user][:role]
    @user.active = params[:user][:active]
    @user.password = params[:user][:password]
    if @user.update_user_attributes
      flash[:notice] = "#{@user.proper_name} is updated."
      redirect_to @user
    else
      render :action => 'edit'
    end
  end
  
  def reset_password
    @user = User.find(params[:id])
  end
  
  def password_reset
    @user = User.find(params[:user_id])
    if params[:password] != params[:password_confirmation]
      flash[:error] = "Passwords do not match."
      redirect_to reset_password(@user)
    else
      User.reset_password(params[:password],params[:user_id])
      flash[:notice] = "Password has been changed."
      redirect_to @user
    end
    
    
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Successfully removed #{@user.proper_name} from Arbeit."
    redirect_to users_url
  end
end

app/views/users/_completed_tasks.html.erb
<div class="well">
	<h3><%= pluralize @completed_tasks.size, 'Task' %> Completed</h3>
	<ul>
		<% @completed_tasks.each do |task| %>
			<li><%= link_to task.name, task_path(task) %>&nbsp;&nbsp;(<%= task.project.name %> - <%= task.updated_at.strftime("%m/%d") %>)</li>
		<% end %>
	</ul>
</div>

app/views/users/_created_tasks.html.erb
<div class="well">
	<h3><%= pluralize @created_tasks.size, 'Task' %> Created</h3>
	<ul>
		<% @created_tasks.each do |task| %>
			<li><%= link_to task.name, task_path(task) %>&nbsp;&nbsp;(<%= task.project.name %> - <%= task.created_at.strftime("%m/%d") %>)</li>
		<% end %>
	</ul>
</div>

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> User</legend>

		<%= f.input :first_name %>
		<%= f.input :last_name %>
		<%= f.input :email %>
		
		<%= f.input :password %>
		<%= f.input :password_confirmation %>
		
		<%= f.input :active %>
		<% if current_user && current_user.role?(:admin) %>
			<%= f.input :role, :collection => User::ROLES, :prompt => true %>
		<% end %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', users_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/users/_user_details.html.erb
<h3>
  <b>Name</b>: <%= @user.proper_name %>
</h3><br>

<p>
  <b>Email</b>: <%= mail_to @user.email, @user.email, encode: "javascript" %>
</p>

<p><b>Current Assignments:</b>
  <% if @user_assignments.empty? %>
    &nbsp;&nbsp;<em>No assignments at this time</em>
  <% else %>
    <ul>
  		<% @user_assignments.each do |assignment| %>
  			<li><%= link_to assignment.project.name, project_path(assignment.project) %></li>
  		<% end %>
  	</ul>
  <% end %>
</p>


<p>
  <b>Role</b>: <%= @user.role.capitalize %>
</p>

<p>
  <b>Active</b>: <%= @user.active ? "Yes" : "No" %>
</p>

app/views/users/edit.html.erb
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<h2>Users</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
			<th>Current Projects</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= mail_to user.email, user.email %></td>
				<td>
					<%= user.projects.current.map(&:name).join(', ') %>
				</td>
        <td>
          <%= link_to raw("<i class='icon-pencil'></i> Edit"), edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to raw("<i class='icon-trash icon-white'></i> Remove"), user_path(user), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @users, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>


<%= link_to raw("<i class='icon-plus icon-white'></i> Add a New User"), new_user_path, :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%= render :partial => 'form' %>

app/views/users/reset_password.html.erb
<h3>Reset Password for <%= @user.name %></h3>

<%= form_tag password_reset_path do %>

	<div class="control-group">
    <%= label_tag :password %>
    <div class="controls">
      <%= password_field_tag :password %>
    </div>
  </div>

	<div class="control-group">
    <%= label_tag :password_confirmation %>
    <div class="controls">
      <%= password_field_tag :password_confirmation %>
    </div>
  </div>

	<!-- TODO: Make sure someone can't tamper with this hidden field -->
	<%= hidden_field_tag :user_id, @user.id %>

  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>

app/views/users/show.html.erb
<div class="row">
	<div class="span7">
		<%= render :partial => "user_details" %>
	</div>
	<div class="span5">
		<%= render :partial => "created_tasks" unless @created_tasks.empty?%>
		<%= render :partial => "completed_tasks" unless @completed_tasks.empty? %>
	</div>
</div>

<div class="form-actions">
  <%= link_to raw("<i class='icon-th-list'></i> Display All Users"), users_path, :class => 'btn'  %>&nbsp;&nbsp;
  <%= link_to raw("<i class='icon-pencil'></i> Edit #{@user.proper_name}"), edit_user_path(@user), :class => 'btn' %>&nbsp;&nbsp;
	<% if @user.id == current_user.id %>
		<%= link_to raw("<i class='icon-wrench icon-white'></i> Reset Password"), reset_password_path(@user), :class => 'btn btn-inverse' %>
	<% else %>
		<%= link_to raw("<i class='icon-trash icon-white'></i> Delete #{@user.proper_name}"), user_path(@user), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
	<% end %>
  
</div>