config/routes.rb
Arbeit::Application.routes.draw do

  # Routes for main resources
  resources :domains
  resources :projects
  resources :tasks
  resources :assignments
  resources :users
  resources :sessions
  
  # Authentication routes
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'reset_password/:id' => 'users#reset_password', :as => :reset_password
  match 'password_reset' => 'users#password_reset', :as => :password_reset
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  # Semi-static page routes
  match 'home' => 'home#home', :as => :home
  match 'search' => 'home#search', :as => :search
  match 'cylon' => 'errors#cylon', :as => :cylon
  match 'statics' => 'statics#show', :as => 'statics'
  
  # Set the root url
  root :to => 'home#home'  
  
  # Named routes
  match 'completed/:id' => 'tasks#complete', :as => :complete
  match 'incomplete/:id' => 'tasks#incomplete', :as => :incomplete
  
  # Last route in routes.rb that essentially handles routing errors
  match '*a', :to => 'errors#routing'
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  # Relationships
  has_many :tasks, :dependent => :destroy
  has_many :assignments, :dependent => :destroy
  has_many :users, :through => :assignments
  belongs_to :domain
  belongs_to :manager, :class_name => "User", :foreign_key => "manager_id"
  
  # allow tasks to be nested within project
  accepts_nested_attributes_for :tasks, :reject_if => lambda { |task| task[:name].blank? }, :allow_destroy => true
  
  # Scopes
  scope :alphabetical,  order("name")
  scope :current,       where("start_date <= ? and (end_date > ? or end_date is null)", Time.now.to_date, Time.now.to_date)
  scope :past,          where("end_date < ?", Time.now)
  scope :for_name,      lambda { |name| where("name LIKE ?", name + "%") }
  
  # Validations
  validates_presence_of :name
  validates_date :start_date
  validates_date :end_date, :after => :start_date, allow_blank: true
  validate :domain_is_active_in_system
  
  
  # Other methods
  def is_active?
    return true if end_date.nil?
    (start_date <= Date.today) && (end_date > Date.today)
  end
  
  private
  def domain_is_active_in_system
    all_active_domains = Domain.active.all.map{|d| d.id}
    unless all_active_domains.include?(self.domain_id)
      errors.add(:domain_id, "is not an active domain in the system")
    end
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :check_login
  authorize_resource

  def index
    @current_projects = Project.current.alphabetical.paginate(:page => params[:page]).per_page(7)
    @past_projects = Project.past.alphabetical
  end

  def show
    @project = Project.find(params[:id])
    authorize! :read, @project
    @project_tasks = @project.tasks.chronological.by_priority.paginate(:page => params[:page]).per_page(10)
    @project_assignments = @project.assignments.by_user.paginate(:page => params[:page]).per_page(8)
  end

  def new
    @project = Project.new
    task = @project.tasks.build
  end

  def edit
    @project = Project.find(params[:id])
    # if shortcut access via projects#index
    if !params[:status].nil? && params[:status] == 'end'
      @project.update_attribute(:end_date, Time.now.to_date)
      flash[:notice] = "#{@project.name} was ended as of today."
      redirect_to projects_path
    end
    # else prepare the dates for display
    @project.start_date = humanize_date @project.start_date
    @project.end_date = humanize_date @project.end_date
    
  end

  def create
    @project = Project.new(params[:project])
    @project.manager_id = current_user.id 
    @project.start_date = convert_to_date(params[:project][:start_date]) # unless params[:project][:start_date].blank?
    @project.end_date = convert_to_date(params[:project][:end_date]) # unless params[:project][:end_date].blank?
    
    if @project.save
      # if saved to database
      flash[:notice] = "#{@project.name} has been created."
      redirect_to @project # go to show project page
    else
      # return to the 'new' form
      render :action => 'new'
    end
  end

  def update    
    @project = Project.find(params[:id])
    params[:project][:start_date] = convert_to_date(params[:project][:start_date])
    params[:project][:end_date] = convert_to_date(params[:project][:end_date])

    # students will commonly edit these fields and see no persistent data
    @project.description = params[:project]
    @project.name = params[:name]
    @project.domain_id = params[:domain_id]
    
    if @project.save
      flash[:notice] = "#{@project.name} has been updated."
      redirect_to @project
    else
      render :action => 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Successfully removed #{@project.name} from Arbeit."
    redirect_to projects_url
  end
end

app/views/projects/_current_projects.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start Date</th>
			<th>End Date</th>
			<th class="centered">Assigned</th>
      <th class="centered">Options</th>
    </tr>
  </thead>
  <tbody>
    <% @current_projects.each do |project| %>
			<% if can? :read, project %>
	      <tr>
	        <td><%= link_to project.name, project_path(project) %></td>
					<td><%= project.start_date.strftime("%b %d, %Y") %></td>
	        <td><%= project.end_date.strftime("%b %d, %Y") %></td>
					<td class="centered"><%= project.assignments.active.size %></td>
	        <td>
						<%= link_to raw("<i class='icon-user icon-white'></i> Assign Person"), new_assignment_path(:id => project.id, :source => 'project'), :class => 'btn btn-mini btn-info' %>
						<%= link_to raw("<i class='icon-remove icon-white'></i> End Project"), edit_project_path(project, :status => 'end'), :confirm => "Are you sure you want to end the #{project.name} project today?", :class => 'btn btn-mini btn-danger' %>
					</td>
	      </tr>
			<% end %>
    <% end %>
  </tbody>
</table>
<%= will_paginate @current_projects, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>	

app/views/projects/_form.html.erb
<%= simple_form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Project</legend>

		<%= f.input :name %>
		<%= f.input :manager_id, :collection => User.active.alphabetical, :include_blank => true %>
		<%= f.input :start_date, :label => "Start Date", :as => :string, :input_html => {:class => "datepicker"} %>		
		<%= f.input :end_date, :label => "End Date", :as => :string, :input_html => {:class => "datepicker"} %>
		<%= f.input :domain_id, :collection => Domain.active.alphabetical, :include_blank => true %>
		<%= f.input :description, :input_html => { :rows => 4 } %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', projects_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/projects/_past_projects.html.erb
<div class="well">
	<h3>Past Projects</h3>
	<ul>
		<% @past_projects.each do |project| %>
			<% if can? :read, project %>
				<li><%= link_to project.name, project_path(project) %>&nbsp;&nbsp;(<%= project.start_date.strftime("%m/%y") %> - <%= project.end_date.strftime("%m/%y") %>)</li>
			<% end %>
		<% end %>
	</ul>
</div>

app/views/projects/_project_assignments.html.erb
<h3>Project Assignments</h3>
<table class="table">
  <thead>
    <tr>
      <th>Person</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @project_assignments.each do |assignment| %>
      <tr>
        <td>
					<%= link_to assignment.user.proper_name, user_path(assignment.user) %>
					<% if !assignment.active %>
						<span class="label label-warning">Inactive</span>
					<% end %>
				</td>
        <td>
					<% if assignment.active %>
						<%= link_to raw("<i class='icon-user icon-white'></i> Make Inactive"), edit_assignment_path(assignment, :status => 'deactivate_prj'), :class => 'btn btn-mini btn-warning' %>
					<% else %>
						<%= link_to raw("<i class='icon-user icon-white'></i> Make Active&nbsp;&nbsp;"), edit_assignment_path(assignment, :status => 'activate_prj'), :class => 'btn btn-mini btn-info' %>
					<% end %>
					<%= link_to raw("<i class='icon-trash icon-white'></i> Destroy Assignment"), assignment_path(assignment), :method => 'delete', :confirm => "Are you sure you want to destroy this assignment?", :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
		<tr>
			<td><%= link_to raw("<i class='icon-plus icon-white'></i> Add New Person"), new_assignment_path(:id => @project.id), :class => 'btn btn-small btn-primary' %></td>
			<td>&nbsp;</td>
		</tr>
  </tbody>
</table>
<%= will_paginate @project_assignments, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>


<%# link_to 'Assign New Person', new_assignment_path(:id => @project.id), :class => 'btn btn-small btn-primary' %>

app/views/projects/_project_details.html.erb
<h2>Project: <%= @project.name %> &nbsp;&nbsp;<%= link_to raw("<i class='icon-pencil'></i> Edit"), edit_project_path(@project), :class => 'btn btn-mini' %></h2><br>

<p>
  <b>Manager</b>: <%= @project.manager.proper_name %>
</p>

<p>
  <b>Project dates</b>: 
	<%= @project.start_date.strftime("%B %d, %Y") %> - 
	<%= @project.end_date.strftime("%B %d, %Y") unless @project.end_date.nil? %> 
	<% if @project.is_active? %>
		&nbsp;&nbsp;<em>(expected)</em>
	<% end %>
</p>

<!-- Guys, I know we want users to be able to use html tags in description, but I'm a little nervous with this. Can someone make sure it's safe? -->
<p>
  <b>Description</b>:<br>
  <%= raw @project.description %>
</p>

<p>
  <b>Domain</b>: <%= @project.domain.name %>
</p>

app/views/projects/_project_fields.html.erb
<%= f.input :name %>
<%= f.input :manager_id, :collection => User.active.alphabetical, :include_blank => true %>
<%= f.input :start_date, :label => "Start Date", :as => :string, :input_html => {:class => "datepicker"} %>		
<%= f.input :end_date, :label => "End Date", :as => :string, :input_html => {:class => "datepicker"} %>
<%= f.input :domain_id, :collection => Domain.active.alphabetical, :include_blank => true %>
<%= f.input :description, :input_html => { :rows => 4 } %>

app/views/projects/_project_tasks.html.erb
<h3>Project Tasks</h3>
<table class="table table-striped">
  <thead>
    <tr>
			<th>Done</th>
      <th>Name</th>
      <th>Due Date</th>
			<th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @project_tasks.each do |task| %>
      <tr>
				<td><%= link_to(raw("<i class='icon-ok icon-white'></i>"), edit_task_path(task, :status => 'completed', :from => 'project'), :class => 'btn btn-mini btn-info') unless task.status == 'Completed' %></td>
        <td><%= link_to task.name, task_path(task) %></td>
				<td><%= task.due_on.strftime("%m/%d/%y") %></td>
        <td><%= raw(task_label(task.status)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @project_tasks, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>

<%= link_to raw("<i class='icon-plus icon-white'></i> Add New Task"), new_task_path(:project_id => @project.id), :class => 'btn btn-small btn-primary' %>

app/views/projects/_task_fields.html.erb
<div class="fields">
	<div class="min_task">
			<%= f.link_to_remove(image_tag("/images/icons/close.gif", :border => 0)) %>
			<%= f.input :name, :label => "Task" %>
			<%= f.input :due_string, :label => "Due" %>
			<%= f.input :priority, :collection => Task::PRIORITY_LIST %>
			<%= f.input :created_by, :as => :hidden, :input_html => { :value => current_user.id } %>
	</div>
</div>

app/views/projects/edit.html.erb
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<div class="row">
	<div class="span8">
		<h3>Current Projects</h3>
		<%= render :partial => "current_projects" %>
	</div>
	<div class="span4">
		<%= render :partial => "past_projects" unless @past_projects.empty? %>
	</div>
</div>

<%= link_to raw("<i class='icon-plus icon-white'></i> Add a New Project"), new_project_path, :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%= simple_nested_form_for @project, :html => { :class => 'form-horizontal' } do |project_form| %>
	<div class="row">
		<div class="span7">
			<fieldset>
		    <legend><%= controller.action_name.capitalize %> Project</legend>
					<%= render "project_fields", :f => project_form %>
		  </fieldset>
		</div>
		<div class="span5">
			<legend>Add some tasks to this project</legend>
			<div id="project_tasks">
				
				<%= project_form.simple_fields_for :tasks do |task_form| %>
					<%= render "task_fields", :f => task_form %>
				<% end %> <!-- end of one tasks form -->
				<p>
					<%# project_form.link_to_add "Add Task", :tasks %>
					<%= project_form.link_to_add(raw("<i class='icon-plus icon-white'></i> Add Task"), :tasks, :class => 'btn btn-mini btn-primary') %>
				</p>
				
			</div> <!-- end of project_tasks div -->
		</div>
	</div>
	<div class="form-actions">
    <%= project_form.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/show.html.erb
<div class="row">
	<div class="span7">
		<%= render :partial => "project_details" %>
		<br />
		<%= render :partial => "project_assignments" unless @project_assignments.empty? %>
	</div>
	<div class="span5">
		<%= render :partial => "project_tasks" unless @project_tasks.empty? %>
	</div>
</div>

<div class="form-actions">
  <%= link_to raw("<i class='icon-th-list'></i> Display All Projects"), projects_path, :class => 'btn'  %>&nbsp;&nbsp;
  <%= link_to raw("<i class='icon-pencil'></i> Edit #{@project.name}"), edit_project_path(@project), :class => 'btn' %>&nbsp;&nbsp;
  <%= link_to raw("<i class='icon-trash icon-white'></i> Delete #{@project.name}"), project_path(@project), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>