config/routes.rb
Arbeit::Application.routes.draw do

  # Routes for main resources
  resources :domains
  resources :projects
  resources :tasks
  resources :assignments
  resources :users
  resources :sessions
  
  # Authentication routes
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'reset_password/:id' => 'users#reset_password', :as => :reset_password
  match 'password_reset' => 'users#password_reset', :as => :password_reset
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  # Semi-static page routes
  match 'home' => 'home#home', :as => :home
  match 'search' => 'home#search', :as => :search
  match 'cylon' => 'errors#cylon', :as => :cylon
  match 'statics' => 'statics#show', :as => 'statics'
  
  # Set the root url
  root :to => 'home#home'  
  
  # Named routes
  match 'completed/:id' => 'tasks#complete', :as => :complete
  match 'incomplete/:id' => 'tasks#incomplete', :as => :incomplete
  
  # Last route in routes.rb that essentially handles routing errors
  match '*a', :to => 'errors#routing'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arbeit :: <%= controller.controller_name.capitalize %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
	<!-- Not sure what this csrf_meta_tags does, so I'm commenting it out for now... -->
	<!-- Somebody needs to take a look at this later when they have some free time. -->
	<%# csrf_meta_tags %>
</head>
<body>
	<%= link_to(image_tag('arbeit_title.png'), home_path) %>
	<div id="wrapper">
		<!-- NAV BAR -->
		<div class="navbar">
		  <div class="navbar-inner">
		    <div class="container">
		      <a class="btn btn-navbar" data-toggle="collapse" data-target=".collapse">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </a>
		      <div class="nav-collapse">
		        <ul class="nav">
							<li><%= link_to "Dashboard", home_path %></li>
		          <li><%= link_to "Projects", projects_path %></li>
		          <li><%= link_to "Tasks", tasks_path %></li>
							<% if logged_in? && current_user.role == "admin" %>
		          	<li><%= link_to "Assignments", assignments_path %></li>
								<li><%= link_to "Users", users_path %></li>
								<li><%= link_to "Domains", domains_path %></li>
							<% end %>
		        </ul>
						<% if logged_in? %>
							<p class="ident pull-right">
								Welcome, <%= link_to current_user.email, user_path(current_user) %> | 
								<%= link_to "Logout", logout_path %>
							</p>
						<% end %>
		      </div>
		    </div>
		  </div>
		</div>

		<!-- MAIN CONTENT -->
		<div class="container">
			<!-- flash messages -->
			<% flash.each do |name, msg| %>
				<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
					<a class="close" data-dismiss="alert">&times;</a>
					<%= msg %>
				</div>
	    <% end %>
			<div class="row">
				<!-- main content placed here -->
				<div id="main_content">
				  <div class="span12">
  					<%= yield %>
  				</div>
				</div>
			</div>
		</div>

		<!-- FOOTER -->
		<footer id="footer">
	    <div class="container">
				<%= render :partial => "partials/footer" %>
	    </div>
	  </footer>
	</div>
</body>
</html>

app/views/layouts/bare.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BSG 75 is coming after you...</title>
  <%= stylesheet_link_tag "bare", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= yield %>
</body>
</html>